apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestao-pokemon-depl
  labels:
    app: gestao-pokemon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestao-pokemon
  template:
    metadata:
      labels:
        app: gestao-pokemon
    spec:
      containers:
        - name: auth
          image: alexandrecordajunior/gestao-pokemon
---
apiVersion: v1
kind: Service
metadata:
  name: gestao-pokemon-srv
  labels:
    app: gestao-pokemon
spec:
  selector:
    app: gestao-pokemon
  ports:
    - name: gestao-pokemon
      protocol: TCP
      port: 80
      targetPort: 80
